"""
Demo script for Groq + Snowflake adaptive intelligence integration.

This demonstrates:
1. Snowflake stores historical payload intelligence
2. Groq generates adaptive payloads based on historical success
3. Results are stored back in Snowflake for continuous learning
"""
import asyncio
import os
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from rico.ai.adaptive_payloads import AdaptivePayloadGenerator
from rico.db.retrieve import get_top_successful_payloads, get_payload_statistics
from rico.db.snowflake_client import is_snowflake_enabled

console = Console()

load_dotenv()


async def demo_adaptive_intelligence():
    """Demonstrate adaptive intelligence integration."""
    
    console.print("\n[bold cyan]═══════════════════════════════════════════════════════════[/bold cyan]")
    console.print("[bold cyan]  RICO Adaptive Intelligence Demo (Groq + Snowflake)      [/bold cyan]")
    console.print("[bold cyan]═══════════════════════════════════════════════════════════[/bold cyan]\n")
    
    # Check Snowflake
    if not is_snowflake_enabled():
        console.print("[red]✗ Snowflake not configured[/red]")
        console.print("[yellow]Set SNOWFLAKE_USER, SNOWFLAKE_PASSWORD, SNOWFLAKE_ACCOUNT in .env[/yellow]\n")
        return
    
    console.print("[green]✓ Snowflake Intelligence Warehouse: ENABLED[/green]")
    
    # Check Groq
    groq_key = os.getenv("GROQ_API_KEY")
    if not groq_key:
        console.print("[red]✗ Groq API not configured[/red]")
        console.print("[yellow]Set GROQ_API_KEY in .env[/yellow]\n")
        return
    
    console.print(f"[green]✓ Groq AI Reasoning Engine: ENABLED[/green]")
    console.print(f"[dim]  API Key: {groq_key[:10]}...{groq_key[-4:]}[/dim]\n")
    
    # Initialize generator
    generator = AdaptivePayloadGenerator()
    
    # Demo 1: SQL Injection Intelligence
    console.print(Panel.fit(
        "[bold]Demo 1: SQL Injection Adaptive Payloads[/bold]",
        border_style="cyan"
    ))
    
    # Retrieve historical intelligence from Snowflake
    console.print("\n[cyan]Step 1:[/cyan] Retrieving historical intelligence from Snowflake...")
    historical_sqli = get_top_successful_payloads("SQL Injection", limit=5)
    stats_sqli = get_payload_statistics("SQL Injection")
    
    if historical_sqli:
        table = Table(title="Historical Successful SQL Injection Payloads", show_header=True)
        table.add_column("#", style="dim")
        table.add_column("Payload", style="yellow")
        
        for idx, payload in enumerate(historical_sqli, 1):
            table.add_row(str(idx), payload[:80] + "..." if len(payload) > 80 else payload)
        
        console.print(table)
        
        if stats_sqli:
            console.print(f"\n[dim]Statistics:[/dim]")
            console.print(f"  Total attempts: {stats_sqli.get('total_attempts', 0)}")
            console.print(f"  Successful: {stats_sqli.get('successful', 0)}")
            console.print(f"  Success rate: {stats_sqli.get('success_rate', 0)}%")
    else:
        console.print("[yellow]No historical SQL injection payloads found in Snowflake[/yellow]")
    
    # Generate adaptive payload using Groq
    console.print("\n[cyan]Step 2:[/cyan] Generating adaptive payload using Groq AI...")
    
    adaptive_sqli = generator.generate_adaptive_sqli_payload(
        api_framework="FastAPI",
        endpoint_context="GET /users/{id}"
    )
    
    if adaptive_sqli:
        console.print(Panel(
            f"[bold green]{adaptive_sqli}[/bold green]",
            title="[bold]Groq-Generated Adaptive Payload[/bold]",
            border_style="green"
        ))
        console.print("[dim]This payload was generated by analyzing historical success patterns[/dim]")
    else:
        console.print("[yellow]Could not generate adaptive payload[/yellow]")
    
    # Demo 2: IDOR Intelligence
    console.print("\n\n" + "─" * 60 + "\n")
    console.print(Panel.fit(
        "[bold]Demo 2: IDOR Adaptive Strategy[/bold]",
        border_style="cyan"
    ))
    
    # Retrieve historical IDOR intelligence
    console.print("\n[cyan]Step 1:[/cyan] Retrieving historical IDOR patterns from Snowflake...")
    historical_idor = get_top_successful_payloads("IDOR", limit=5)
    stats_idor = get_payload_statistics("IDOR")
    
    if historical_idor:
        table = Table(title="Historical Successful IDOR Patterns", show_header=True)
        table.add_column("#", style="dim")
        table.add_column("Pattern", style="yellow")
        
        for idx, pattern in enumerate(historical_idor, 1):
            table.add_row(str(idx), pattern[:80] + "..." if len(pattern) > 80 else pattern)
        
        console.print(table)
        
        if stats_idor:
            console.print(f"\n[dim]Statistics:[/dim]")
            console.print(f"  Total attempts: {stats_idor.get('total_attempts', 0)}")
            console.print(f"  Successful: {stats_idor.get('successful', 0)}")
            console.print(f"  Success rate: {stats_idor.get('success_rate', 0)}%")
    else:
        console.print("[yellow]No historical IDOR patterns found in Snowflake[/yellow]")
    
    # Generate adaptive IDOR strategy using Groq
    console.print("\n[cyan]Step 2:[/cyan] Generating adaptive IDOR strategy using Groq AI...")
    
    adaptive_idor = generator.generate_adaptive_idor_payload(
        api_framework="FastAPI",
        endpoint_context="GET /users/{user_id}/orders"
    )
    
    if adaptive_idor:
        strategy_text = adaptive_idor.get("strategy", "N/A")
        test_ids = adaptive_idor.get("test_ids", [])
        
        console.print(Panel(
            f"[bold]Strategy:[/bold] {strategy_text}\n\n"
            f"[bold]Test IDs:[/bold] {', '.join(map(str, test_ids))}",
            title="[bold]Groq-Generated IDOR Strategy[/bold]",
            border_style="green"
        ))
        console.print("[dim]This strategy was generated by analyzing historical IDOR success patterns[/dim]")
    else:
        console.print("[yellow]Could not generate adaptive IDOR strategy[/yellow]")
    
    # Summary
    console.print("\n\n" + "═" * 60)
    console.print("\n[bold green]✓ Adaptive Intelligence Integration Working![/bold green]\n")
    
    console.print("[bold]Architecture:[/bold]")
    console.print("  1. [cyan]Snowflake[/cyan] stores historical payload intelligence")
    console.print("  2. [cyan]Groq AI[/cyan] analyzes patterns and generates adaptive payloads")
    console.print("  3. [cyan]RICO[/cyan] executes payloads and stores results back in Snowflake")
    console.print("  4. [cyan]Continuous Learning[/cyan] - system improves over time\n")
    
    console.print("[bold]Next Steps:[/bold]")
    console.print("  • Run scans to populate Snowflake with more intelligence")
    console.print("  • Adaptive payloads will automatically improve as data grows")
    console.print("  • Monitor success rates in Snowflake analytics\n")


if __name__ == "__main__":
    asyncio.run(demo_adaptive_intelligence())
